### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by CyberKid1987** [Roylyre/Routersploit-Termux#2]
Please update your script. Thank you 🙂

**Comment by Zedack** [comment]
This happens when i use python rsf.py


Traceback (most recent call last):
  File "/data/data/com.termux/files/home/routersploit/rsf.py", line 10, in <module>
    from routersploit.interpreter import RoutersploitInterpreter
  File "/data/data/com.termux/files/home/routersploit/routersploit/interpreter.py", line 12, in <module>
    from future.builtins import input
ModuleNotFoundError: No module named 'future'
